// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:trading_app/features/alerts/data/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AlertDirectionAdapter());
    registerAdapter(AlertKindAdapter());
    registerAdapter(AlertStatusAdapter());
    registerAdapter(PriceAlertAdapter());
    registerAdapter(QuoteSideAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AlertDirectionAdapter());
    registerAdapter(AlertKindAdapter());
    registerAdapter(AlertStatusAdapter());
    registerAdapter(PriceAlertAdapter());
    registerAdapter(QuoteSideAdapter());
  }
}
